# Übungszettel 1: Python

## Maschinelles Lernen - WiSe 23/24

### Abgabe 25.10.2023, 23:55 Uhr

*Hinweise:*
- Übungsaufgaben **müssen** in Gruppen von 3-4 Personen abgegeben werden. 
- Es wird pro Übungszettel nur eine Aufgabe bewertet, die übrigen Aufgaben dienen zur selbstständigen Vertiefung des Vorlesungsstoffs. Für diese Aufgaben werden nach der Abgabe Musterlösungen bereitgestellt.
- Die Lösungen sollen in diesem IPython Notebook realisiert werden, wobei Teilaufgaben und Zwischenergebnisse ausgegeben bzw. visualisiert werden sollen.
- Für die Abgabe sollen Sie dieses IPython Notebook und ggf. zugehörige Dateien in ein **Ziparchiv** packen und im Ilias hochladen. Das Ziparchiv soll nach folgendem Muster benannt werden:
`UebungXX_Nachname1_Nachname2_Nachname3.zip`, wobei die Nachnamen in alphabetischer Reihenfolge angegeben und Umlaute ggf. ersetzt werden sollen.

---

## Aufgabe 1: Python Grundlagen

a) Schreiben Sie ein Programm, welches für einen vom Benutzer eingegebenen Wert die Fibonacci Zahlen berechnet und ausgibt.

In [3]:
#fibonacci numbers

def fib(n):
    if n == 0:
        return 0
    if n == 1:
        return 1
    else:
        return fib(n-1) + fib(n-2)
    
print(fib(5))
print(fib(10))

5
55


b) Lösen Sie die ersten beiden Aufgaben auf http://www.pythonchallenge.com.

In [51]:
#secrete message to be decoded
message = "g fmnc wms bgblr rpylqjyrc gr zw fylb. rfyrq ufyr amknsrcpq ypc dmp. bmgle gr gl zw fylb gq glcddgagclr ylb rfyr'q ufw rfgq rcvr gq qm jmle. sqgle qrpgle.kyicrpylq() gq pcamkkclbcb. lmu ynnjw ml rfc spj"

def decode(mess, a, b):
    #find index in the alphabet of a and b
    shift = (ord(b)-97) - (ord(a)-97)
    
    # creat a list of encrypted words.
    ciphertext = mess.split()    
    #create a list of decoded words
    decoded = []
    
    # define characters to ignore
    ignore_chars = ['.', '(', ')','\'']
    
    for ch in ciphertext:
        cipher_ords = [ord(x) for x in ch]                      #convert each letter to its ascii value
        #decoded_ords = [((x + shift)) % 122  for x in cipher_ords]   #shift each letter by the shift value
        decoded_ords = []
        for x in cipher_ords:
            if chr(x) in ignore_chars:
                decoded_ords.append(x) 
            elif x+shift <= 122:
                decoded_ords.append(x  + shift)
            else:
                decoded_ords.append( (x + shift) % 122 + 96)    
        decoded_chrs = [chr(x) for x in decoded_ords]             #convert each ascii value to a letter
        decode_word = ''.join(decoded_chrs)                      #join the letters to form a word
        decoded.append(decode_word)                             #append each decoded word to the list of decoded words    
           
    decoded = ' '.join(decoded)                                  #join the words to form a sentence       
    return decoded

print(decode(message, 'k', 'm'))  

i hope you didnt translate it by hand. thats what computers are for. doing it in by hand is inefficient and that's why this text is so long. using string.maketrans() is recommended. now apply on the url
{


c) Schreiben Sie eine Funktion, die die $n$ größten Werte in einem Numpy Array berechnet und messen Sie die Laufzeit für $n=5$ für ein Array der Größe 100000.

In [9]:
import numpy as np

#create an array for length 100000
random_array = np.random.rand(100000)
#sort this array ascending
random_array[::-1].sort()
#cal 5 biggest val
sum = sum(random_array[:5])

print(sum)



4.9998616284240835


---
## Aufgabe 2: List Comprehensions

Die folgenden Teilaufgaben sollen, wo immer es möglich ist, mittels List Comprehensions gelöst werden.

a) Erzeugen Sie eine Liste der Zahlen 1 bis 1000. Danach erzeugen Sie daraus eine neue Liste, die alle ungeraden Zahlen der ersten Liste quadriert enthält.

In [8]:
import random

l = [random.randint(1, 1000) for _ in range(10)] 

l_2 = [i*2 for i in l if i % 2 == 1]

print(l)
print(l_2)

[442, 356, 792, 248, 254, 806, 862, 931, 509, 789]
[1862, 1018, 1578]


b) Der Hamming-Abstand von Binärcodes ist definiert als $ h(x, y) := | \{j \in \{1, ... , l\} | x_j  \neq y_j \} |$ wobei $ j \in {0, 1} $. Schreiben Sie ein Programm, das zunächst zwei zufällige Binärcodes der Länge $l$ generiert und anschließend ihren Hamming-Abstand berechnet. Berechnen Sie dann die Hammingdistanz für zwei Codes der Länge $l=10$.

*Hinweis:* Benutzen Sie die Funktion `zip`. Eine genaue Beschreibung der Funktion erhält man durch `print zip.__doc__`

In [42]:
import random

def generate_random_binary_code(l):
    return [random.choice([0, 1]) for _ in range(l)]

def hamming_distance_binary_code(x, y):
    if len(x) != len(y):
        raise ValueError("Die Binärcodes müssen die gleiche Länge haben.")
    return sum(el1 != el2 for el1, el2 in zip(x, y))

l = 10

binary_code1 = generate_random_binary_code(l)
binary_code2 = generate_random_binary_code(l)

hamming_distance = hamming_distance_binary_code(binary_code1, binary_code2)

print(f"Der Hamming-Abstand der Binärcodes {binary_code1} und {binary_code2} beträgt {hamming_distance}.")


Der Hamming-Abstand der Binärcodes [1, 1, 0, 1, 1, 0, 0, 0, 1, 0] und [0, 1, 0, 0, 0, 1, 1, 1, 1, 1] beträgt 7.


c) Gegeben sind die Listen `a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]` und `b = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]`. Schreiben Sie ein Programm, das daraus eine Liste erzeugt, die nur jene Elemente enthält, die in beiden Listen vorkommen.

In [7]:
a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
b = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

commen_elements = set(a) & set(b)
print(commen_elements)

{1, 2, 3, 5, 8, 13}


---
## Aufgabe 3: Higher Order Functions

Schreiben Sie ein Programm, das eine Liste von Wörtern auf eine Liste von Zahlen abbildet, wobei die Zahlen die Länge der Wörter repräsentieren. Schreiben Sie das Programm in drei Varianten: 

a) mit einer for-Schleife

In [22]:
import random
import string

def generate_random_string():
    length = random.randint(1,15)
    letters = string.ascii_lowercase
    return ''.join(random.choice(letters) for _ in range(length))

word_list = [generate_random_string() for _ in range(10)]
word_list_length = []

for str in word_list:
    word_list_length.append(len(str))

print(word_list)
print(word_list_length)

['zccakt', 'co', 'fxcqvk', 'bt', 'txtlnqildvxtut', 'hvhvv', 'mbjuelq', 'tptu', 'amzshltekguv', 'alztvarqieuwvbt']
[6, 2, 6, 2, 14, 5, 7, 4, 12, 15]


b) mit der Funktion `map()` 

In [24]:
word_list_length_2 = list(map(lambda x: len(x), word_list))

print(word_list_length_2) 

[6, 2, 6, 2, 14, 5, 7, 4, 12, 15]


c) mit List Comprehensions.

In [25]:
word_list_length_3 =[len(x) for x in word_list]

print(word_list_length_3)

[6, 2, 6, 2, 14, 5, 7, 4, 12, 15]


---
## **Aufgabe 4: Matrizen (bewertet: 1+1,5+1,5+1 Punkte)**
*Hinweis:* In den folgenden Aufgaben darf, sofern nicht anders angegeben, nur reines Python ohne zusätzliche Bibliotheken verwendet werden (insbesondere kein `numpy` für Matrixoperationen).
Eine Matrix kann in Python durch zwei verschachtelte Listen dargestellt werden
Zum Beispiel kann die Matrix

$A = \begin{pmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9\\
\end{pmatrix}$ 

in Python wie folgt angegeben werden:

`a = [ [1,2,3], [4,5,6], [7,8,9] ]`


a) Schreiben Sie eine Funktion, die eine $n \times n$-Matrix transponiert und testen Sie diese mit einem Beispiel.

In [31]:
import unittest

def transpose(a):
    t = [ [a[j][i] for j in range(len(a))] for i in range(len(a[0]))]
    return t

a = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

a_t = [
    [1, 4, 7],
    [2, 5, 8],
    [3, 6, 9]   
]

if(a_t == transpose(a)):
    print("Function transpose() funktionert")
else:
    print("Error")

Function transpose() funktionert


b) Schreiben Sie eine Funktion, die zwei $n \times n$ Matrizen addiert und testen Sie diese mit einem Beispiel.

In [6]:
matrix1 = [ [1, 2, 3,10],
            [4, 5, 6,11],
            [7, 8, 9,12]   ]

matrix2 = [ [9, 8, 7,10],
            [6, 5, 4,11],
            [3, 2, 1,12]   ]

res = [[0 for j in range(len(matrix1[0]))] for i in range(len(matrix1))]
    
for i in range(len(matrix1)):
    for j in range(len(matrix1[0])):
        res[i][j] = matrix1[i][j] + matrix2[i][j]
    
print(res)        

[[10, 10, 10, 20], [10, 10, 10, 22], [10, 10, 10, 24]]


c) Schreiben Sie eine Funktion, die zwei $n \times n$ Matrizen multipliziert und testen Sie diese mit einem Beispiel.

In [37]:
def mul_matrix(matrix1, matrix2):
    result = [[0 for _ in range(len(matrix2[0]))] for _ in range(len(matrix1))]

    for i in range(len(matrix1)):
        for j in range(len(matrix2[0])):
            for k in range(len(matrix2)):
                result[i][j] += matrix1[i][k] * matrix2[k][j]

    return result

res_matrix = mul_matrix(matrix1,matrix2)
print(res_matrix)

[[30, 24, 18], [84, 69, 54], [138, 114, 90]]


d) Validieren Sie die Ergebnisse der Funktionen aus den vorigen Aufgabenteilen, indem Sie die jeweiligen Matrixoperationen in `numpy` berechnen und die Ergebnisse vergleichen.

In [40]:
import numpy as np

# Matrixaddition mit numpy
add_result_numpy = np.add(matrix1, matrix2)
print("Ergebnis der Matrixaddition mit numpy:")
print(add_result_numpy)

# Matrixmultiplikation mit numpy
mul_result_numpy = np.dot(matrix1, matrix2)
print("\nErgebnis der Matrixmultiplikation mit numpy:")
print(mul_result_numpy)



Ergebnis der Matrixaddition mit numpy:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Ergebnis der Matrixmultiplikation mit numpy:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
