# Übungszettel 1: Python (Musterlösung)

## Maschinelles Lernen - WiSe 23/24

### Abgabe 25.10.2023, 23:55 Uhr

Übungsaufgaben **müssen** in Gruppen von 3-4 Personen abgegeben werden. Alle Lösungen sollen in diesem IPython Notebook realisiert werden, wobei Teilaufgaben und Zwischenergebnisse ausgegeben bzw. visualisiert werden sollen.
Das IPython Notebook und ggf. zugehörige Dateien müssen in ein **Ziparchiv** gepackt werden und in Ilias hochgeladen werden. Das Ziparchiv soll nach folgendem Muster benannt werden:
`UebungXX_Nachname1_Nachname2_Nachname3.zip`, wobei die Nachnamen in alphabetischer Reihenfolge angegeben und Umlaute ggf. ersetzt werden sollen.

---

## Aufgabe 1: Python Grundlagen

a) Schreiben Sie ein Programm, welches für einen vom Benutzer eingegebenen Wert die Fibonacci Zahlen berechnet und ausgibt.

In [1]:
def fibo(n):
    if n <= 1:
        return n
    else:
        return(fibo(n-1) + fibo(n-2))

# Test der Funktion
for i in range(10):
    print(str(i) + ": " + str(fibo(i)))

b) Lösen Sie die ersten beiden Aufgaben auf http://www.pythonchallenge.com.

In [1]:
# Task 0:
print("Next URL: http://www.pythonchallenge.com/pc/def/" + str(2**38) + ".html")
print()

Next URL: http://www.pythonchallenge.com/pc/def/274877906944.html



In [2]:
# Task 1:

from string import ascii_lowercase

table = str.maketrans(ascii_lowercase, ascii_lowercase[2:] + ascii_lowercase[:2])

text = "g fmnc wms bgblr rpylqjyrc gr zw fylb. rfyrq ufyr amknsrcpq ypc dmp. bmgle gr gl zw fylb gq glcddgagclr ylb rfyr'q ufw rfgq rcvr gq qm jmle. sqgle qrpgle.kyicrpylq() gq pcamkkclbcb. lmu ynnjw ml rfc spj."

print(text.translate(table))
print()
print("Next URL: http://www.pythonchallenge.com/pc/def/" + "map".translate(table) + ".html")


i hope you didnt translate it by hand. thats what computers are for. doing it in by hand is inefficient and that's why this text is so long. using string.maketrans() is recommended. now apply on the url.

Next URL: http://www.pythonchallenge.com/pc/def/ocr.html


c) Schreiben Sie eine Funktion, die die $n$ größten Werte in einem Numpy Array berechnet und messen Sie die Laufzeit für $n=5$ für ein Array der Größe 100000.

In [4]:
import numpy as np

top_n = 5

values = np.random.randint(1,100000, 10000000)
values2 = np.copy(values)

In [5]:
%%time

print(np.sort(values)[-top_n:])

[99999 99999 99999 99999 99999]
CPU times: user 544 ms, sys: 1.75 ms, total: 546 ms
Wall time: 549 ms


In [6]:
%%time

index = np.argpartition(values, -top_n)[-top_n:]

print(values[index])
print()


[99999 99999 99999 99999 99999]

CPU times: user 67.3 ms, sys: 3.28 ms, total: 70.6 ms
Wall time: 73.4 ms


---
## Aufgabe 2: List Comprehensions

Die folgenden Teilaufgaben sollen, wo immer es möglich ist, mittels List Comprehensions gelöst werden.

a) Erzeugen Sie eine Liste der Zahlen 1 bis 1000. Danach erzeugen Sie daraus eine neue Liste, die alle ungeraden Zahlen der ersten Liste quadriert enthält.

In [3]:
values = [ x for x in range(1,1001) ]

print(values)

squared_odd_values = [ x**2 for x in values[::2] ]

print(squared_odd_values)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 22

b) Der Hamming-Abstand von Binärcodes ist definiert als $ h(x, y) := | \{j \in \{1, ... , l\} | x_j  \neq y_j \} |$ wobei $ j \in {0, 1} $. Schreiben Sie ein Programm, das zunächst zwei zufällige Binärcodes der Länge $l$ generiert und anschließend ihren Hamming-Abstand berechnet. Berechnen Sie dann die Hammingdistanz für zwei Codes der Länge $l=10$.

*Hinweis:* Benutzen Sie die Funktion `zip`. Eine genaue Beschreibung der Funktion erhält man durch `print zip.__doc__`

In [8]:
from random import randint

def random_binary(length):
    return [randint(0,1) for _ in range(length)]

def hamming_distance(bincode0, bincode1):
    return len([1 for (x,y) in (zip(bincode0, bincode1)) if x!=y])

a = random_binary(10)
b = random_binary(10)

print(a)
print(b)
print("Distance: " + str(hamming_distance(a,b)))

[0, 1, 1, 1, 1, 1, 0, 0, 1, 0]
[1, 1, 0, 1, 0, 1, 0, 0, 0, 1]
Distance: 5


c) Gegeben sind die Listen `a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]` und `b = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]`. Schreiben Sie ein Programm, das daraus eine Liste erzeugt, die nur jene Elemente enthält, die in beiden Listen vorkommen.

In [9]:
a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
b = [1,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

print(set([x for x in a if x in b]))

{1, 2, 3, 5, 8, 13}


---
## Aufgabe 3: Higher Order Functions

Schreiben Sie ein Programm, das eine Liste von Wörtern auf eine Liste von Zahlen abbildet, wobei die Zahlen die Länge der Wörter repräsentieren. Schreiben Sie das Programm in drei Varianten: a) mit einer for-Schleife, b) mit der Funktion `map()` und c) mit List Comprehensions.

In [10]:
words = ["a", "ab", "abc", "abcd", "abc"]

# imperative approach
counts = []
for w in words:
    counts.append(len(w))
print(counts)

# functional approach
counts = list(map(lambda w: len(w), words))
print(counts)
    
# list comprehension
counts = [ len(w) for w in words ]
print(counts)

[1, 2, 3, 4, 3]
[1, 2, 3, 4, 3]
[1, 2, 3, 4, 3]


---
## **Aufgabe 4: Matrizen (bewertet: 1+1,5+1,5+1 Punkte)**
*Hinweis:* In den folgenden Aufgaben darf, sofern nicht anders angegeben, nur reines Python ohne zusätzliche Bibliotheken verwendet werden (insbesondere kein `numpy` für Matrixoperationen).
Eine Matrix kann in Python durch zwei verschachtelte Listen dargestellt werden
Zum Beispiel kann die Matrix

$A = \begin{pmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9\\
\end{pmatrix}$ 

in Python wie folgt angegeben werden:

`a = [ [1,2,3], [4,5,6], [7,8,9] ]`


a) Schreiben Sie eine Funktion, die eine $n \times n$-Matrix transponiert und testen Sie diese mit einem Beispiel.

In [1]:
a = [[1,2,3], [4,5,6], [7,8,9]]

def transpose(mat):
    rows = len(mat)
    cols = len(mat[0])
    return [[mat[j][i] for j in range(rows)] for i in range(cols)]

transpose(a)

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]

b) Schreiben Sie eine Funktion, die zwei $n \times n$ Matrizen addiert und testen Sie diese mit einem Beispiel.

In [4]:
def mat_add(mat1, mat2):
    rows = len(mat1)
    cols = len(mat1[0])
    return [[mat1[i][j] + mat2[i][j] for j in range(cols)] for i in range(rows)]


b = [[10,20,30], [40,50,60],[70,80,90]] 

mat_add(a,b)

[[11, 22, 33], [44, 55, 66], [77, 88, 99]]

c) Schreiben Sie eine Funktion, die zwei $n \times n$ Matrizen multipliziert und testen Sie diese mit einem Beispiel.

In [6]:
def inner_product(v1, v2):
    return sum([v1[i]*v2[i] for i in range(len(v1))])
    

def mat_mul(mat1, mat2):
    mat1_rows = len(mat1)
    mat2_cols = len(mat2[0])
    mat2_t = transpose(mat2)
    return [[inner_product(mat1[i], mat2_t[j]) for j in range(mat2_cols)] for i in range(mat1_rows)]


c = [[2,2],[3,3],[4,4]]

mat_mul(a,c)

[[20, 20], [47, 47], [74, 74]]

d) Validieren Sie die Ergebnisse der Funktionen aus den vorigen Aufgabenteilen, indem Sie die jeweiligen Matrixoperationen in `numpy` berechnen und die Ergebnisse vergleichen.

In [20]:
import numpy as np 

assert (np.asarray(a).T == transpose(a)).all(), "2.1 ist Falsch"
assert (np.add(a, b) == mat_add(a,b)).all() , "2.2 ist Falsch"
assert (np.matmul(a,c) == mat_mul(a,c)).all(), "2.3 ist Falsch"

In [17]:
np.matmul(a,c)

array([[20, 20],
       [47, 47],
       [74, 74]])